name: CI
on:
  push:
    tags:
      - "v*"
jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.1'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --split-per-abi --release
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*apk"
          token: ${{ secrets.GH_TOKEN }}